[pytest]
testpaths = tests
addopts = -ra -p no:cacheprovider
markers =
    positive_smoke: stable positive smoke integration API tests
    negative: negative integration API tests
    extended: extended integration API tests
    users_extended: extended users integration API tests
    organizations_extended: extended organizations integration API tests
    employees_extended: extended employees integration API tests
    permissions_extended: extended permissions integration API tests
    auth_extended: extended auth integration API tests
    mass_extended: extended mass integration API tests
    security_extended: extended security integration API tests
    consistency: consistency integration API flow tests
    email_confirmation_extended: extended email confirmation API tests
    phone_mass_extended: extended phone precreate and phone mass API tests
    captcha_extended: extended captcha exclude API tests
    integrator_extended: extended integrator API tests
    certificates_extended: extended certificate API tests
